apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo
  namespace: default
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/dawidtomczynski/demo-crm
    targetRevision: HEAD
    path: demo
  destination: 
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
